### ISSUE TITLE
timing for the bank ..

### ISSUE THREAD

**Issue by Armagryzor** [Sighmir/vrp_bank#1]
Hi Sighmir,

I have some troubles to change the timing of the bank.  i tried to edited this piece of code:

RegisterNetEvent('es_bank:currentlyrobbing')
AddEventHandler('es_bank:currentlyrobbing', function(robb)
	robbing = true
	bank = robb
	secondsRemaining = 300
end)

secondsRemaining = 300 to secondsRemaining = 900 

But at 610 secondes i received the money!?!

Thank's

**Comment by Sighmir** [comment]
Its not that simple, the timer for the bank runs on client and on server side players can't cheat. I give no support for modifying the code.
